### ISSUE TITLE
`timeout_msecs` column unused?

### ISSUE THREAD

**Issue by Turbo87** [rafaelcaricio/backie#7]
I might be reading the code wrong, but it looks like the `timeout_msecs` column is never actually used anywhere. Am I missing something? 😅

**Comment by rafaelcaricio** [comment]
It is not used at the moment. Not all features are implemented at the moment. I'm happy to review and accept code changes. :)

**Comment by Turbo87** [comment]
ah, I see, thanks for the explanation. I thought I may have misread the code 😄
